#### Nombre: **02_preprocessing**
#### Autores: _Sergio Cañón  Laiz y Ignacio Ruiz de Zuazu Echavarría_
#### CUNEF
#### 15/01/2021


# Librerías

In [1]:
# importamos librerías 

import numpy as np  # álgebra lineal
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Conv2D, MaxPooling2D, AveragePooling2D, GlobalAveragePooling2D
from tensorflow.keras import utils
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import glob  # pathnames
import cv2  # lectura y procesamiento de las imagenes

import matplotlib.pyplot as plt  # gráficos
import matplotlib.image as mpimg

import os  # lectura de directorios

import keras 
from keras.layers import *
from keras.models import *
from keras.utils.np_utils import to_categorical
from keras import backend as K
from keras import optimizers
import time #tiempos de ejecución
from random import shuffle
from keras.preprocessing import image
import imageio


from tensorflow.keras.preprocessing import image
import matplotlib.pyplot as plt
from keras.optimizers import SGD

from numpy import savetxt


# Importación de datos

In [13]:
# carpeta con imagenes procesadas

onlyfiles = os.listdir(r"..\\data\\02_processed\\")
size = len(onlyfiles)
print("La longuitud del los datos son de:", len(onlyfiles))

La longuitud del los datos son de: 24099


In [14]:
# shuffle para que las imagenes estén mezcladas y no nos distorsione el train y test set

shuffle(onlyfiles)


# Tratamiento de la variable objetivo

Para clasificar las imagenes, parseamos el nombre del fichero por el número (edad) antes de la primera barra baja. Segundo, plantemos el problema como uno de clasificación por lo que agrupamos las edades en intervalos.

In [15]:
#split nombre de cada .JPG

race = [i.split('_')[2] for i in onlyfiles]
age = [i.split('_')[0] for i in onlyfiles]
gender = [i.split('_')[1] for i in onlyfiles]

## Raza

In [16]:
#creación de grupos por r

categorical_labels_race = to_categorical(race, num_classes=5)
categorical_labels_race[:5]



array([[0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.]], dtype=float32)

In [20]:
np.save(r'../data/04_data_array/categorical_labels_race.npy', categorical_labels_race)

## Edad

In [21]:
#creación de grupos por edad en fucnion de lso percentiles calculados en el EDA

classes = []
for i in age:
    i = int(i)
    if i <= 19:
        classes.append(0)
    if (i>19) and (i<=26):
        classes.append(1)
    if (i>26) and (i<34):
        classes.append(2)
    if (i>=34) and (i<50):
        classes.append(3)
    if i>=50:
        classes.append(4)
        
categorical_labels_age = to_categorical(classes, num_classes=5)
categorical_labels_age[:5]


array([[0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)

In [23]:
np.save('../data/04_data_array/categorical_labels_age.npy', categorical_labels_age)

## Gender

In [24]:
#creación de grupos por r

categorical_labels_gender = to_categorical(gender, num_classes=2)
categorical_labels_gender[:5]



array([[0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.]], dtype=float32)

In [25]:
np.save('../data/04_data_array/categorical_labels_gender.npy', categorical_labels_gender)

# Prepocessing RGB


El primer paso será importar las imágenes es escala de grises y transformalas a un tamaño de 32 x 32 píxeles.

In [39]:
X_data =[]

for file in onlyfiles:
    face = cv2.imread(file) # importacion de imágenes   
    face = cv2.resize(face, (32, 32) ) # reducción y estandarización del tamaño
    X_data.append(face)  # añadimos cada imagen a la variable

In [40]:
# Transformación del píxeles en valores numéricos

X = np.squeeze(X_data)
print( "(Numero de imágenes, Pixeles altura, Píxeles anchura, Dimensión): ", X.shape) # comprobacion del tamaño

(Numero de imágenes, Pixeles altura, Píxeles anchura, Dimensión):  (24099, 32, 32, 3)


La normalización de las imagenes se produce dividiendo cada valor del array entre 255 puesto que ese número es el mayor valor que puede tener un píxel en una imagen transformada a array.

In [41]:
# Normalización

X = X.astype('float32')
X /= 255 

In [44]:
from numpy import savetxt


# define data

data_32_32_rgb = X

# guardamos las imagenes en array para mayor velocidad de carga en los mdoelos

np.save('../data/04_data_array/data_32_32_rgb.npy', data_32_32_rgb)



# Prepocessing 128x128


In [28]:
X_data =[]

for file in onlyfiles:
    face = cv2.imread(file) # importacion de imágenes   
    face = cv2.resize(face, (128, 128) ) # reducción y estandarización del tamaño
    X_data.append(face)  # añadimos cada imagen a la variable

In [29]:
# Transformación del píxeles en valores numéricos

X = np.squeeze(X_data)
print( "(Numero de imágenes, Pixeles altura, Píxeles anchura, Dimensión): ", X.shape) # comprobacion del tamaño

(Numero de imágenes, Pixeles altura, Píxeles anchura, Dimensión):  (24099, 128, 128, 3)


In [30]:
# Normalización

X = X.astype('float32')
X /= 255 

In [34]:


# define data
data_128_128_rgb = X

# save file

np.save('../data/04_data_array/data_128_128_rgb.npy', data_128_128_rgb)

